
# leave this here! it puts the main element on the screen
Body:

<Body@BoxLayout>:
    
<MainMenu>:
    # inherits from BoxLayout

    # these below mean nothing right now... I may want to specify in dp anyway
    # size_hint_x: 50
    # size_hint_y: 80

    Button:
        text: "Colors"

    Button:
        text: "Palettes"

    Button
        text: "Donate"

<ColorMenu>:
    # inherits from BoxLayout

<PaletteMenu>:
    # inherits from BoxLayout

<DonateMenu>:
    # inherits from BoxLayout